### ISSUE TITLE
Prevents for multi currency support

### ISSUE THREAD

**Issue by MantasR** [paysafegroup/paysafe_sdk_nodejs#5]
https://github.com/paysafegroup/paysafe_sdk_nodejs/blob/24c17048ec9f917ae6f866a335ffef5f563c1015/lib/PaysafeApiClient.js#L119-L147

The marked area mean that your SDK ignores the account id and other details (like apiKey, apiPassword and environment),
If it was passed before, even if I am using a completely different instance of PaysafeApiClient.

`
var cardService;
var customerService;
var directDebitService;
var threeDsecureService;
`

Are static variables which are kept for a runtime of app (until next restart).

This means if I ran a server and someone made a payment in GBP, ALL FURTHER TRANSACTION WILL BE IN GBP, NO MATTER WHAT I PASS IN.
Same would happen if first transaction would be in USD, EUR.

**Comment by FreakenK** [comment]
Fixed by PR #8

**Comment by asawarivaidya** [comment]
This issue has been fixed, thanks!
